### ISSUE TITLE
Unable to clone repo in docker container

### ISSUE THREAD

**Issue by jack-zheng** [jack-zheng/analyser#3]
log show as:

2019-02-21 05:12:20,036 INFO reaped unknown pid 19
[2019-02-21 05:12:20,040] ERROR in app: Exception on /webhook [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/views.py", line 42, in webhook
    webhookrepo = Repo.clone_from(url=repourl, to_path=repopath)
  File "/usr/local/lib/python3.6/site-packages/git/repo/base.py", line 988, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/git/repo/base.py", line 939, in _clone
    finalize_process(proc, stderr=stderr)
  File "/usr/local/lib/python3.6/site-packages/git/util.py", line 333, in finalize_process
    proc.wait(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/git/cmd.py", line 415, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v https://github.xxx.xxx.xxx/bizx/au-usermanagement.git ./au-usermanagement
  stderr: 'Cloning into './au-usermanagement'...
fatal: unable to access 'https://github.xxx.xxx.xxx/bizx/au-usermanagement.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
'

**Comment by jack-zheng** [comment]
fix by add 'RUN git config --global http.sslVerify false' to Dockfile.

but another issue occur, when clone repo, it require username and pwd. 
in order to resolve this, put those info into clone URL and put it to config file to avoid expose user sensitive info

**Comment by jack-zheng** [comment]
Fix
